baseURL = "https://lockwood.fun/"
languageCode = "en-us"
title = "Lockwoods Having Fun Writing Code"
theme = "ananke"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
enableRobotsTXT = true
disableKinds = ["taxonmyTerm"]

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  github = "https://github.com/sumnercreations/hugo-blog"
  background_color_class = "bg-dark-gray"
  recent_posts_number = 3
  show_reading_time = true
  custom_css = ["css/custom_main.css"]

[taxonomies]
  contributor = "contributors"
  tag = "tags"
  category = "categories"